-- Create waitlist table
CREATE TABLE public.waitlist (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email text NOT NULL,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT waitlist_pkey PRIMARY KEY (id),
  CONSTRAINT waitlist_email_unique UNIQUE (email)
);

-- Create app_config table for storing configuration
CREATE TABLE public.app_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  key_name text NOT NULL,
  key_value text NOT NULL,
  environment text DEFAULT 'production'::text,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT app_config_pkey PRIMARY KEY (id),
  CONSTRAINT app_config_key_env_unique UNIQUE (key_name, environment)
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

-- Create policies for waitlist table
CREATE POLICY "Allow anonymous inserts" ON public.waitlist FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role to read all" ON public.waitlist FOR SELECT USING (auth.role() = 'service_role');

-- Create policies for app_config table (only service role can access)
CREATE POLICY "Allow service role full access to config" ON public.app_config USING (auth.role() = 'service_role');

-- Insert initial configuration (replace with your actual keys when deploying)
INSERT INTO public.app_config (key_name, key_value, environment, description) VALUES
  ('RESEND_API_KEY', 'your_resend_api_key_here', 'production', 'Resend API key for sending emails'),
  ('NEXT_PUBLIC_SUPABASE_URL', 'https://uwnfgigdzbxgsdhckhha.supabase.co', 'production', 'Supabase project URL'),
  ('NEXT_PUBLIC_SUPABASE_ANON_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bmZnaWdkemJ4Z3NkaGNraGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4OTc1MDMsImV4cCI6MjA3OTQ3MzUwM30.2VNhJ-5u_U76xFVn1hAt_7vlWrOi2TlSBU_soI8ygfU', 'production', 'Supabase anon key');